# Use official Node.js 24 LTS slim image
FROM node:24-slim

# Install PM2 globally
RUN npm install -g pm2

# Set working directory
WORKDIR /usr/src/app

# Build-time arguments
ARG NODE_ENV=production
ARG PORT
ARG DATABASE_USERS_URL
ARG DATABASE_REKLAMACIJE_URL
ARG DATABASE_OTPAD_URL
ARG DATABASE_ODSUSTVA_URL
ARG DATABASE_NABAVKE_URL
ARG ACCESS_TOKEN_SECRET
ARG REFRESH_TOKEN_SECRET
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG GITHUB_CLIENT_ID
ARG GITHUB_CLIENT_SECRET
ARG FACEBOOK_CLIENT_ID
ARG FACEBOOK_CLIENT_SECRET

# Set runtime environment variables inside container
ENV NODE_ENV=$NODE_ENV
ENV PORT=$PORT
ENV DATABASE_USERS_URL=$DATABASE_USERS_URL
ENV DATABASE_REKLAMACIJE_URL=$DATABASE_REKLAMACIJE_URL
ENV DATABASE_OTPAD_URL=$DATABASE_OTPAD_URL
ENV DATABASE_ODSUSTVA_URL=$DATABASE_ODSUSTVA_URL
ENV DATABASE_NABAVKE_URL=$DATABASE_NABAVKE_URL
ENV ACCESS_TOKEN_SECRET=$ACCESS_TOKEN_SECRET
ENV REFRESH_TOKEN_SECRET=$REFRESH_TOKEN_SECRET
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID
ENV GITHUB_CLIENT_SECRET=$GITHUB_CLIENT_SECRET
ENV FACEBOOK_CLIENT_ID=$FACEBOOK_CLIENT_ID
ENV FACEBOOK_CLIENT_SECRET=$FACEBOOK_CLIENT_SECRET

# Copy package.json & package-lock.json first (for caching)
COPY package*.json ./

# Install dependencies
RUN npm ci --omit=dev

# Copy the rest of the source
COPY . .

# Build the TypeScript project
RUN npm run prisma:generate:all
RUN npm run build



# Expose port (same as your app)
EXPOSE 5000

# Command to run the app
CMD ["pm2-runtime", "./dist/server.js", "--name", "shoppy-apps-backend"]