import { z } from "zod";

export const envSchema = z.object({
  PORT: z.string().default("5000"),
  DATABASE_USERS_URL: z.string(),
  DATABASE_REKLAMACIJE_URL: z.string(),
  DATABASE_OTPAD_URL: z.string(),
  DATABASE_ODSUSTVA_URL: z.string(),
  DATABASE_NABAVKE_URL: z.string(),
  ACCESS_TOKEN_SECRET: z.string().min(10),
  REFRESH_TOKEN_SECRET: z.string().min(10),
  GOOGLE_CLIENT_ID: z.string().optional(),
  GOOGLE_CLIENT_SECRET: z.string().optional(),
  GOOGLE_CALLBACK_URL: z.string().optional(),
  GITHUB_CLIENT_ID: z.string().optional(),
  GITHUB_CLIENT_SECRET: z.string().optional(),
  GITHUB_CALLBACK_URL: z.string().optional(),
  FACEBOOK_CLIENT_ID: z.string().optional(),
  FACEBOOK_CLIENT_SECRET: z.string().optional(),
  FACEBOOK_CALLBACK_URL: z.string().optional(),
});

export const userSensitiveDataSchema = z.object({
  userId: z.number().int(),
  firstName: z.string().min(3, "First name is required"),
  lastName: z.string().min(3, "Last name is required"),
  email: z.email("Invalid email"),
  passwordHash: z.string().nullable().optional(),
  refreshToken: z.string().nullable().optional(),
  roleId: z.number().int(),
});

export const queryParamsSchema = z.object({
  sortBy: z.string().optional(),
  sortOrder: z.enum(["asc", "desc"]).optional(),
  limit: z.string().optional(),
  page: z.string().optional(),
  search: z.string().optional(),
  filters: z.record(z.string(), z.string()).optional(),
});

export const userDataSchema = z.object({
  userId: z.number().int(),
  firstName: z.string().min(3, "First name is required"),
  lastName: z.string().min(3, "Last name is required"),
  email: z.email("Invalid email"),
  roleId: z.number().int(),
  roleName: z.string(),
});

export const jwtPayloadSchema = userDataSchema.extend({
  iat: z.number(),
  exp: z.number(),
});


export const reklamacijaSchema = z.object({
  idReklamacije: z.number().int().optional(), // autogenerated
  brojReklamacije: z.string().min(3, "Broj reklamacije is required"),
  zemljaReklamacije: z.enum(["SRBIJA", "CRNA_GORA"], "Zemlja reklamacije is required"),
  datumPrijema: z.coerce.date().optional(),
  odgovornaOsoba: z.string().optional(),
  imePrezime: z.string().min(3, "Ime i prezime is required"),
  adresa: z.string().optional(),
  telefon: z
    .string()
    .min(6, "Telefon is required and must have at least 6 characters")
    .max(20, "Telefon must have at most 20 characters")
    .regex(/^[\d+\s\-()/]+$/, "Telefon contains invalid characters"),
  email: z.email("invalid email").optional(),
  datumKupovine: z.date().optional(),
  brojRacuna: z.string().min(3, "Broj racuna is required").optional(),
  nazivProizvoda: z.string().optional(),
  opisReklamacije: z.string().min(10, "Opis reklamacije is too short").optional(),
  datumOdgovora: z.date().optional(),
  opisOdluke: z.string().min(10, "Opis odluke is too short").optional(),
  komentar: z.string().optional(),
  smsSent: z.boolean().default(false),
  statusReklamacije: z.enum([
    "PRIJEM",
    "OBRADA",
    "OPRAVDANA",
    "NEOPRAVDANA",
    "DODATNI_ROK",
  ], "Status reklamacije is required"),
  files: z.array(z.object({
    fileName: z.string().min(1, "File name is required"),
    fileUrl: z.string().url("Invalid file URL"),
  })).optional(),
});
