import { z } from "zod";

export const envSchema = z.object({
  PORT: z.string().default("5000"),
  DATABASE_USERS_URL: z.string(),
  DATABASE_REKLAMACIJE_URL: z.string(),
  DATABASE_OTPAD_URL: z.string(),
  DATABASE_ODSUSTVA_URL: z.string(),
  DATABASE_NABAVKE_URL: z.string(),
  ACCESS_TOKEN_SECRET: z.string().min(10),
  REFRESH_TOKEN_SECRET: z.string().min(10),
  GOOGLE_CLIENT_ID: z.string().nullable().optional(),
  GOOGLE_CLIENT_SECRET: z.string().nullable().optional(),
  GOOGLE_CALLBACK_URL: z.string().nullable().optional(),
  GITHUB_CLIENT_ID: z.string().nullable().optional(),
  GITHUB_CLIENT_SECRET: z.string().nullable().optional(),
  GITHUB_CALLBACK_URL: z.string().nullable().optional(),
  FACEBOOK_CLIENT_ID: z.string().nullable().optional(),
  FACEBOOK_CLIENT_SECRET: z.string().nullable().optional(),
  FACEBOOK_CALLBACK_URL: z.string().nullable().optional(),
});

export const userSensitiveDataSchema = z.object({
  userId: z.number().int(),
  firstName: z.string().min(3, "First name is required"),
  lastName: z.string().min(3, "Last name is required"),
  email: z.email("Invalid email"),
  passwordHash: z.string().nullable().nullable().optional(),
  refreshToken: z.string().nullable().nullable().optional(),
  roleId: z.number().int(),
});

export const queryParamsSchema = z.object({
  sortBy: z.string().nullable().optional(),
  sortOrder: z.enum(["asc", "desc"]).nullable().optional(),
  limit: z.string().nullable().optional(),
  page: z.string().nullable().optional(),
  search: z.string().nullable().optional(),
  filters: z.record(z.string(), z.string()).nullable().optional(),
});

export const userDataSchema = z.object({
  userId: z.number().int(),
  firstName: z.string().min(3, "First name is required"),
  lastName: z.string().min(3, "Last name is required"),
  email: z.email("Invalid email"),
  roleId: z.number().int(),
  roleName: z.string(),
});

export const jwtPayloadSchema = userDataSchema.extend({
  iat: z.number(),
  exp: z.number(),
});

export const reklamacijaSchema = z.object({
  idReklamacije: z.number().int().nullable().optional(), // autogenerated
  brojReklamacije: z.string().min(3, "Broj reklamacije is required"),
  zemljaReklamacije: z.enum(["SRBIJA", "CRNA_GORA"], "Zemlja reklamacije is required"),
  datumPrijema: z.coerce.date().nullable().optional(),
  odgovornaOsoba: z.string().nullable().optional(),
  imePrezime: z.string().min(3, "Ime i prezime is required"),
  adresa: z.string().nullable().optional(),
  telefon: z
    .string()
    .min(6, "Telefon is required and must have at least 6 characters")
    .max(20, "Telefon must have at most 20 characters")
    .regex(/^[\d+\s\-()/]+$/, "Telefon contains invalid characters"),
  email: z.email("invalid email").nullable().optional(),
  datumKupovine: z.coerce.date().nullable().optional(),
  brojRacuna: z.string().min(3, "Broj racuna is required").nullable().optional(),
  nazivProizvoda: z.string().nullable().optional(),
  opisReklamacije: z.string().min(10, "Opis reklamacije is too short").nullable().optional(),
  datumOdgovora: z.coerce.date().nullable().optional(),
  opisOdluke: z.string().min(10, "Opis odluke is too short").nullable().optional(),
  komentar: z.string().nullable().optional(),
  smsSent: z.boolean().default(false),
  statusReklamacije: z.enum(["PRIJEM", "OBRADA", "OPRAVDANA", "NEOPRAVDANA", "DODATNI_ROK"], "Status reklamacije is required"),
  files: z.array(z.string().min(1, "File name is required")).optional(),
});
