name: CI/CD Docker Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/shoppy-backend
      NODE_ENV: production
      DATABASE_USERS_URL: ${{ secrets.DATABASE_USERS_URL }}
      DATABASE_REKLAMACIJE_URL: ${{ secrets.DATABASE_REKLAMACIJE_URL }}
      DATABASE_OTPAD_URL: ${{ secrets.DATABASE_OTPAD_URL }}
      DATABASE_ODSUSTVA_URL: ${{ secrets.DATABASE_ODSUSTVA_URL }}
      DATABASE_NABAVKE_URL: ${{ secrets.DATABASE_NABAVKE_URL }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GITHUB_CLIENT_ID: ${{ secrets.GITHUB_CLIENT_ID }}
      GITHUB_CLIENT_SECRET: ${{ secrets.GITHUB_CLIENT_SECRET }}
      FACEBOOK_CLIENT_ID: ${{ secrets.FACEBOOK_CLIENT_ID }}
      FACEBOOK_CLIENT_SECRET: ${{ secrets.FACEBOOK_CLIENT_SECRET }}

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24
          cache: "npm"

      # 3. Install dependencies and prisma client
      - name: Install dependencies and prisma client
        run: |
          npm ci --include=dev
          npm run prisma:generate:all

      # 4. Run typecheck and lint
      - name: Typecheck & Lint
        run: |
          npm run typecheck
          npm run lint

      # 5. Run tests
      # To do: add run tests

      # 6. Authenticate to GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 7. Build Docker image
      - name: Build Docker image
        run: |
          DOCKER_BUILDKIT=1 docker build \
            --build-arg NODE_ENV=$NODE_ENV \
            --build-arg PORT=${{ secrets.PORT }} \
            --build-arg DATABASE_USERS_URL=${{ secrets.DATABASE_USERS_URL }} \
            --build-arg DATABASE_REKLAMACIJE_URL=${{ secrets.DATABASE_REKLAMACIJE_URL }} \
            --build-arg DATABASE_OTPAD_URL=${{ secrets.DATABASE_OTPAD_URL }} \
            --build-arg DATABASE_ODSUSTVA_URL=${{ secrets.DATABASE_ODSUSTVA_URL }} \
            --build-arg DATABASE_NABAVKE_URL=${{ secrets.DATABASE_NABAVKE_URL }} \
            --build-arg ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }} \
            --build-arg REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }} \
            --build-arg GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
            --build-arg GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
            --build-arg GITHUB_CLIENT_ID=${{ secrets.GITHUB_CLIENT_ID }} \
            --build-arg GITHUB_CLIENT_SECRET=${{ secrets.GITHUB_CLIENT_SECRET }} \
            --build-arg FACEBOOK_CLIENT_ID=${{ secrets.FACEBOOK_CLIENT_ID }} \
            --build-arg FACEBOOK_CLIENT_SECRET=${{ secrets.FACEBOOK_CLIENT_SECRET }} \
            -t $IMAGE_NAME:latest .

      # 8. Push Docker image to GHCR
      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:latest

      # 9. Deploy container remote server
      - name: Deploy container
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
          docker pull $IMAGE_NAME:latest;
          docker stop shoppy-app-backend || true;
          docker rm shoppy-app-backend || true;
          docker container prune -f
          docker run -d \
          --name shoppy-app-backend \
          --restart unless-stopped \
          --network host \
          -e DATABASE_USERS_URL=${{ secrets.DATABASE_USERS_URL }} \
          -e DATABASE_REKLAMACIJE_URL=${{ secrets.DATABASE_REKLAMACIJE_URL }} \
          -e DATABASE_OTPAD_URL=${{ secrets.DATABASE_OTPAD_URL }} \
          -e DATABASE_ODSUSTVA_URL=${{ secrets.DATABASE_ODSUSTVA_URL }} \
          -e DATABASE_NABAVKE_URL=${{ secrets.DATABASE_NABAVKE_URL }} \
          -e ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }} \
          -e REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }} \
          -e GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
          -e GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
          -e GITHUB_CLIENT_ID=${{ secrets.GITHUB_CLIENT_ID }} \
          -e GITHUB_CLIENT_SECRET=${{ secrets.GITHUB_CLIENT_SECRET }} \
          -e FACEBOOK_CLIENT_ID=${{ secrets.FACEBOOK_CLIENT_ID }} \
          -e FACEBOOK_CLIENT_SECRET=${{ secrets.FACEBOOK_CLIENT_SECRET }} \
          -e PORT=${{ secrets.PORT }} \
          -p ${{ secrets.PORT }}:${{ secrets.PORT }} \
          $IMAGE_NAME:latest
